#pragma once

#include <JuceHeader.h>
#include "BinaryData.h"   // generated by juce_add_binary_data (the MOLECULA fonts)

// MOLECULA design system palette + JUCE LookAndFeel.
namespace molecula {
    inline constexpr juce::uint32 kVoid     = 0xff050508;
    inline constexpr juce::uint32 kGlass    = 0xff0e1020;
    inline constexpr juce::uint32 kPanel    = 0xff131628;
    inline constexpr juce::uint32 kSurface  = 0xff1a1d35;
    inline constexpr juce::uint32 kRim      = 0xff252a48;
    inline constexpr juce::uint32 kPlasma   = 0xff4fc3f7;
    inline constexpr juce::uint32 kPhosphor = 0xffa8e063;
    inline constexpr juce::uint32 kBond     = 0xffe8edf2;
    inline constexpr juce::uint32 kMuted    = 0xff5c6380;
    inline constexpr juce::uint32 kDanger   = 0xffff4b6a;
    inline constexpr juce::uint32 kAmber    = 0xffffb347;
}

class MoleculaLookAndFeel : public juce::LookAndFeel_V4 {
public:
    MoleculaLookAndFeel() {
        using namespace molecula;
        display = juce::Typeface::createSystemTypefaceFor (BinaryData::SpaceGrotesk_ttf, BinaryData::SpaceGrotesk_ttfSize);
        mono    = juce::Typeface::createSystemTypefaceFor (BinaryData::JetBrainsMono_ttf, BinaryData::JetBrainsMono_ttfSize);
        body    = juce::Typeface::createSystemTypefaceFor (BinaryData::Inter_ttf, BinaryData::Inter_ttfSize);

        setColour (juce::ResizableWindow::backgroundColourId, juce::Colour (kVoid));
        setColour (juce::Slider::rotarySliderFillColourId,    juce::Colour (kPlasma));   // per-knob override
        setColour (juce::Slider::textBoxTextColourId,        juce::Colour (kPlasma));
        setColour (juce::Slider::textBoxBackgroundColourId,  juce::Colours::transparentBlack);
        setColour (juce::Slider::textBoxOutlineColourId,     juce::Colours::transparentBlack);
        setColour (juce::ComboBox::backgroundColourId,       juce::Colour (kSurface));
        setColour (juce::ComboBox::textColourId,             juce::Colour (kBond));
        setColour (juce::ComboBox::outlineColourId,          juce::Colour (kRim));
        setColour (juce::ComboBox::arrowColourId,            juce::Colour (kMuted));
        setColour (juce::PopupMenu::backgroundColourId,      juce::Colour (kPanel));
        setColour (juce::PopupMenu::textColourId,            juce::Colour (kBond));
        setColour (juce::PopupMenu::highlightedBackgroundColourId, juce::Colour (kPlasma).withAlpha (0.18f));
        setColour (juce::PopupMenu::highlightedTextColourId, juce::Colour (kPlasma));
        setColour (juce::TextButton::buttonColourId,         juce::Colour (kSurface));
        setColour (juce::TextButton::textColourOnId,         juce::Colour (kPlasma));
        setColour (juce::TextButton::textColourOffId,        juce::Colour (kBond));
        setColour (juce::TextEditor::backgroundColourId,     juce::Colour (kSurface));
        setColour (juce::TextEditor::textColourId,           juce::Colour (kBond));
        setColour (juce::TextEditor::outlineColourId,        juce::Colour (kRim));
        setColour (juce::TextEditor::focusedOutlineColourId, juce::Colour (kPlasma));
        setColour (juce::CaretComponent::caretColourId,      juce::Colour (kPlasma));
        setColour (juce::ToggleButton::textColourId,         juce::Colour (kMuted));
        setColour (juce::ToggleButton::tickColourId,         juce::Colour (kPlasma));
        setColour (juce::ToggleButton::tickDisabledColourId, juce::Colour (kRim));
    }

    // Font helpers — Space Grotesk (display), JetBrains Mono (data), Inter (body).
    juce::Font displayFont (float h) const { return juce::Font (juce::FontOptions (display).withHeight (h)); }
    juce::Font monoFont    (float h) const { return juce::Font (juce::FontOptions (mono).withHeight (h)); }
    juce::Font bodyFont    (float h) const { return juce::Font (juce::FontOptions (body).withHeight (h)); }

    juce::Font getLabelFont (juce::Label&) override                 { return bodyFont (14.0f); }
    juce::Font getComboBoxFont (juce::ComboBox&) override           { return displayFont (13.0f); }
    juce::Font getPopupMenuFont() override                         { return displayFont (13.0f); }
    juce::Font getTextButtonFont (juce::TextButton&, int) override  { return displayFont (12.0f); }
    juce::Font getSliderPopupFont (juce::Slider&) override          { return monoFont (12.0f); }

    void drawRotarySlider (juce::Graphics& g, int x, int y, int w, int h,
                           float pos, float startAngle, float endAngle,
                           juce::Slider& slider) override {
        using namespace molecula;
        const auto accent = slider.findColour (juce::Slider::rotarySliderFillColourId);
        auto bounds = juce::Rectangle<int> (x, y, w, h).toFloat().reduced (6.0f);
        const float radius = juce::jmin (bounds.getWidth(), bounds.getHeight()) * 0.5f;
        const float cx = bounds.getCentreX(), cy = bounds.getCentreY();
        const float arcR = radius - 2.0f;
        const float angle = startAngle + pos * (endAngle - startAngle);
        const juce::PathStrokeType stroke (3.0f, juce::PathStrokeType::curved,
                                                 juce::PathStrokeType::rounded);

        juce::Path track;
        track.addCentredArc (cx, cy, arcR, arcR, 0.0f, startAngle, endAngle, true);
        g.setColour (juce::Colour (kRim));
        g.strokePath (track, stroke);

        juce::Path fill;
        fill.addCentredArc (cx, cy, arcR, arcR, 0.0f, startAngle, angle, true);
        g.setColour (accent);
        g.strokePath (fill, stroke);

        const float bodyR = radius * 0.62f;
        g.setColour (juce::Colour (kGlass));
        g.fillEllipse (cx - bodyR, cy - bodyR, bodyR * 2, bodyR * 2);
        g.setColour (juce::Colour (kRim));
        g.drawEllipse (cx - bodyR, cy - bodyR, bodyR * 2, bodyR * 2, 1.0f);

        const juce::Point<float> p1 (cx + std::sin (angle) * bodyR * 0.4f,
                                     cy - std::cos (angle) * bodyR * 0.4f);
        const juce::Point<float> p2 (cx + std::sin (angle) * bodyR * 0.95f,
                                     cy - std::cos (angle) * bodyR * 0.95f);
        g.setColour (accent);
        g.drawLine ({ p1, p2 }, 2.5f);
        g.setColour (accent.withAlpha (0.6f));
        g.fillEllipse (cx - 2.5f, cy - 2.5f, 5.0f, 5.0f);
    }

    void drawButtonBackground (juce::Graphics& g, juce::Button& b, const juce::Colour&,
                               bool over, bool down) override {
        using namespace molecula;
        auto r = b.getLocalBounds().toFloat().reduced (0.5f);
        auto fill = down ? juce::Colour (kRim) : (over ? juce::Colour (kSurface).brighter (0.12f) : juce::Colour (kSurface));
        g.setColour (fill);
        g.fillRoundedRectangle (r, 6.0f);
        g.setColour (over ? juce::Colour (kPlasma) : juce::Colour (kRim));
        g.drawRoundedRectangle (r, 6.0f, 1.0f);
    }

private:
    juce::Typeface::Ptr display, mono, body;
};
